		fprintf(stderr, "--------------------------------------------------------------------------\n");
		fprintf(stderr, "usage: %s testNo VRMLFile [args] [-MFMax nMFMax] [-log logfile]\n", argv[0]);
		fprintf(stderr, "testNo   ... テスト番号\n");
		fprintf(stderr, " 0 : VRMLFileのパース\n");
		fprintf(stderr, " 1 : ルートノードの子ノード列挙\n");
		fprintf(stderr, " 2 : ノード名の表示\n");
		fprintf(stderr, " 3 : フィールドの表示\n");
		fprintf(stderr, " 4 : Boxノードのフィールドを表示\n");
		fprintf(stderr, " 5 : Transformノードのフィールドを表示\n");
		fprintf(stderr, " 6 : 単純形状の計算\n");
		fprintf(stderr, " 7 : OpenHRP形式ファイルの表示\n");
		fprintf(stderr, " 8 : すべてのDEF名の表示\n");
		fprintf(stderr, " 9 : 指定DEFのノード内容表示\n");
		fprintf(stderr, "nMFMax   ... MFフィールドの値を省略表示（>0)\n");
		fprintf(stderr, "logfile  ... ログの出力先（デフォルトはstderr）\n");
		fprintf(stderr, "(ex)\n");
		fprintf(stderr, "%s 0 sample.x3d\n", argv[0]);
		fprintf(stderr, "%s 1 sample.x3d -MFMax 3\t# MFフィールドは3個だけ表示\n", argv[0]);
		fprintf(stderr, "%s 5 sample.x3d -log out.txt\t# ログをout.txtに出力\n", argv[0]);

